use crate::ids::TaskId;
use chrono::{DateTime, Utc};
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use uuid::Uuid;

/// Category of artifact generated during execution.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactKind {
    /// Plain text output or summary.
    Text,
    /// JSON structured output.
    Json,
    /// Code diff / patch hunk.
    Patch,
    /// Whole file content snapshot.
    FileContent,
    /// Reference to a subagent transcript or turn index.
    TranscriptReference,
    /// Specific code snippet or symbol extract.
    CodeSnippet,
}

/// An immutable piece of evidence or output generated by a task.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    pub id: String,
    pub task_id: TaskId,
    pub name: String,
    pub kind: ArtifactKind,
    pub data: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub created_at: DateTime<Utc>,
}

impl Artifact {
    pub fn new(
        task_id: TaskId,
        name: impl Into<String>,
        kind: ArtifactKind,
        data: impl Into<String>,
    ) -> Self {
        Self {
            id: format!("art-{}", Uuid::new_v4().simple()),
            task_id,
            name: name.into(),
            kind,
            data: data.into(),
            metadata: None,
            created_at: Utc::now(),
        }
    }

    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

/// Snapshot of the context provided to a task before execution.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ContextSnapshot {
    #[serde(default)]
    pub files: Vec<String>,
    #[serde(default)]
    pub symbols: Vec<String>,
    #[serde(default)]
    pub env_summary: Option<String>,
    pub captured_at: DateTime<Utc>,
}

impl ContextSnapshot {
    pub fn new(files: Vec<String>, symbols: Vec<String>, env_summary: Option<String>) -> Self {
        Self {
            files,
            symbols,
            env_summary,
            captured_at: Utc::now(),
        }
    }
}

/// In-memory thread-safe store of artifacts for an orchestration run.
#[derive(Clone, Default)]
pub struct ArtifactStore {
    artifacts: Arc<RwLock<Vec<Artifact>>>,
}

const MAX_ARTIFACTS: usize = 2_048;
const MAX_ARTIFACT_BYTES: usize = 256 * 1024;
const MAX_TOTAL_ARTIFACT_BYTES: usize = 8 * 1024 * 1024;
pub const MAX_INLINE_OUTPUT_BYTES: usize = 256 * 1024;

pub fn truncate_text(mut text: String, max_bytes: usize) -> String {
    if text.len() <= max_bytes {
        return text;
    }

    let original_bytes = text.len();
    let mut truncate_at = max_bytes;
    while !text.is_char_boundary(truncate_at) {
        truncate_at -= 1;
    }
    text.truncate(truncate_at);
    text.push_str(&format!("\n\n[truncated from {original_bytes} bytes]"));
    text
}

impl ArtifactStore {
    pub fn new() -> Self {
        Self {
            artifacts: Arc::new(RwLock::new(Vec::new())),
        }
    }

    pub fn record(&self, mut artifact: Artifact) -> Artifact {
        if artifact.data.len() > MAX_ARTIFACT_BYTES {
            let original_bytes = artifact.data.len();
            let mut truncate_at = MAX_ARTIFACT_BYTES;
            while !artifact.data.is_char_boundary(truncate_at) {
                truncate_at -= 1;
            }
            artifact.data.truncate(truncate_at);
            let metadata = artifact
                .metadata
                .get_or_insert_with(|| serde_json::json!({}));
            if let Some(metadata) = metadata.as_object_mut() {
                metadata.insert("truncated".to_string(), serde_json::Value::Bool(true));
                metadata.insert(
                    "original_bytes".to_string(),
                    serde_json::Value::from(original_bytes as u64),
                );
            }
        }
        let stored_artifact = artifact.clone();
        let mut list = self.artifacts.write();
        list.push(artifact);
        let mut total_bytes = list
            .iter()
            .map(|artifact| artifact.data.len())
            .sum::<usize>();
        while list.len() > MAX_ARTIFACTS || total_bytes > MAX_TOTAL_ARTIFACT_BYTES {
            let Some(artifact) = list.first() else {
                break;
            };
            total_bytes = total_bytes.saturating_sub(artifact.data.len());
            list.remove(0);
        }
        stored_artifact
    }

    pub fn for_task(&self, task_id: &TaskId) -> Vec<Artifact> {
        let list = self.artifacts.read();
        list.iter()
            .filter(|a| &a.task_id == task_id)
            .cloned()
            .collect()
    }

    pub fn all(&self) -> Vec<Artifact> {
        let list = self.artifacts.read();
        list.clone()
    }

    pub fn get(&self, artifact_id: &str) -> Option<Artifact> {
        let list = self.artifacts.read();
        list.iter().find(|a| a.id == artifact_id).cloned()
    }

    pub fn clear(&self) {
        let mut list = self.artifacts.write();
        list.clear();
    }
}
