use crate::ids::TaskId;
use chrono::{DateTime, Utc};
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use uuid::Uuid;

/// Category of artifact generated during execution.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactKind {
    /// Plain text output or summary.
    Text,
    /// JSON structured output.
    Json,
    /// Code diff / patch hunk.
    Patch,
    /// Whole file content snapshot.
    FileContent,
    /// Reference to a subagent transcript or turn index.
    TranscriptReference,
    /// Specific code snippet or symbol extract.
    CodeSnippet,
}

/// An immutable piece of evidence or output generated by a task.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    pub id: String,
    pub task_id: TaskId,
    pub name: String,
    pub kind: ArtifactKind,
    pub data: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub created_at: DateTime<Utc>,
}

impl Artifact {
    pub fn new(
        task_id: TaskId,
        name: impl Into<String>,
        kind: ArtifactKind,
        data: impl Into<String>,
    ) -> Self {
        Self {
            id: format!("art-{}", Uuid::new_v4().simple()),
            task_id,
            name: name.into(),
            kind,
            data: data.into(),
            metadata: None,
            created_at: Utc::now(),
        }
    }

    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

/// Snapshot of the context provided to a task before execution.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ContextSnapshot {
    #[serde(default)]
    pub files: Vec<String>,
    #[serde(default)]
    pub symbols: Vec<String>,
    #[serde(default)]
    pub env_summary: Option<String>,
    pub captured_at: DateTime<Utc>,
}

impl ContextSnapshot {
    pub fn new(files: Vec<String>, symbols: Vec<String>, env_summary: Option<String>) -> Self {
        Self {
            files,
            symbols,
            env_summary,
            captured_at: Utc::now(),
        }
    }
}

/// In-memory thread-safe store of artifacts for an orchestration run.
#[derive(Clone, Default)]
pub struct ArtifactStore {
    artifacts: Arc<RwLock<Vec<Artifact>>>,
}

const MAX_ARTIFACTS: usize = 2_048;
const MAX_ARTIFACT_BYTES: usize = 256 * 1024;
const MAX_TOTAL_ARTIFACT_BYTES: usize = 8 * 1024 * 1024;
pub const MAX_INLINE_OUTPUT_BYTES: usize = 256 * 1024;
pub const MAX_DEPENDENCY_OUTPUT_BYTES: usize = 32 * 1024;
pub const MAX_DEPENDENCY_ARTIFACTS: usize = 16;
pub const MAX_DEPENDENCY_CONTEXT_BYTES: usize = 128 * 1024;

pub fn truncate_text(mut text: String, max_bytes: usize) -> String {
    if text.len() <= max_bytes {
        return text;
    }

    let original_bytes = text.len();
    let suffix = format!("\n\n[truncated from {original_bytes} bytes]");
    if suffix.len() >= max_bytes {
        let mut truncate_at = max_bytes;
        while !suffix.is_char_boundary(truncate_at) {
            truncate_at = truncate_at.saturating_sub(1);
        }
        return suffix[..truncate_at].to_string();
    }

    let mut truncate_at = max_bytes - suffix.len();
    while !text.is_char_boundary(truncate_at) {
        truncate_at = truncate_at.saturating_sub(1);
    }
    text.truncate(truncate_at);
    text.push_str(&suffix);
    text
}

/// Sanitizes a dependency task output before serializing it into downstream context:
/// - Strips verification envelope if present
/// - Strips ANSI terminal escape sequences
/// - Compacts excessive consecutive blank lines
/// - Preserves substantive findings, file references, and test outcomes
pub fn sanitize_dependency_output(output: &str) -> String {
    let stripped = crate::verification::output_without_verification_claim(output);
    let cleaned = strip_terminal_control_sequences(stripped);

    // Collapse more than 2 consecutive newlines into 2
    let mut result = String::with_capacity(cleaned.len());
    let mut newline_count = 0;
    for ch in cleaned.chars() {
        if ch == '\n' {
            newline_count += 1;
            if newline_count <= 2 {
                result.push(ch);
            }
        } else {
            newline_count = 0;
            result.push(ch);
        }
    }
    result.trim().to_string()
}

fn strip_terminal_control_sequences(input: &str) -> String {
    let mut cleaned = String::with_capacity(input.len());
    let mut chars = input.chars().peekable();
    while let Some(character) = chars.next() {
        match character {
            '\x1b' => consume_escape_sequence(&mut chars),
            '\u{009b}' => consume_control_sequence(&mut chars),
            '\u{0090}' | '\u{0098}' | '\u{009d}' | '\u{009e}' | '\u{009f}' => {
                consume_string_sequence(&mut chars)
            }
            '\r' => {
                if !cleaned.ends_with('\n') {
                    cleaned.push('\n');
                }
            }
            '\n' | '\t' => cleaned.push(character),
            character if character.is_control() => {}
            character => cleaned.push(character),
        }
    }
    cleaned
}

fn consume_escape_sequence(chars: &mut std::iter::Peekable<std::str::Chars<'_>>) {
    match chars.next() {
        Some('[') => consume_control_sequence(chars),
        Some(']' | 'P' | 'X' | '^' | '_') => consume_string_sequence(chars),
        Some(character) if (' '..='/').contains(&character) => consume_escape_final(chars),
        Some(_) | None => {}
    }
}

fn consume_escape_final(chars: &mut impl Iterator<Item = char>) {
    for character in chars {
        if character.is_ascii() && ('0'..='~').contains(&character) {
            break;
        }
    }
}

fn consume_control_sequence(chars: &mut impl Iterator<Item = char>) {
    for character in chars {
        if character.is_ascii() && ('@'..='~').contains(&character) {
            break;
        }
    }
}

fn consume_string_sequence(chars: &mut std::iter::Peekable<std::str::Chars<'_>>) {
    while let Some(character) = chars.next() {
        if character == '\x07' {
            break;
        }
        if character == '\u{009c}' {
            break;
        }
        if character == '\x1b' && chars.next_if_eq(&'\\').is_some() {
            break;
        }
    }
}

impl ArtifactStore {
    pub fn new() -> Self {
        Self {
            artifacts: Arc::new(RwLock::new(Vec::new())),
        }
    }

    pub fn record(&self, mut artifact: Artifact) -> Artifact {
        if artifact.data.len() > MAX_ARTIFACT_BYTES {
            let original_bytes = artifact.data.len();
            let mut truncate_at = MAX_ARTIFACT_BYTES;
            while !artifact.data.is_char_boundary(truncate_at) {
                truncate_at -= 1;
            }
            artifact.data.truncate(truncate_at);
            let metadata = artifact
                .metadata
                .get_or_insert_with(|| serde_json::json!({}));
            if let Some(metadata) = metadata.as_object_mut() {
                metadata.insert("truncated".to_string(), serde_json::Value::Bool(true));
                metadata.insert(
                    "original_bytes".to_string(),
                    serde_json::Value::from(original_bytes as u64),
                );
            }
        }
        let stored_artifact = artifact.clone();
        let mut list = self.artifacts.write();
        list.push(artifact);
        let mut total_bytes = list
            .iter()
            .map(|artifact| artifact.data.len())
            .sum::<usize>();
        while list.len() > MAX_ARTIFACTS || total_bytes > MAX_TOTAL_ARTIFACT_BYTES {
            let Some(artifact) = list.first() else {
                break;
            };
            total_bytes = total_bytes.saturating_sub(artifact.data.len());
            list.remove(0);
        }
        stored_artifact
    }

    pub fn for_task(&self, task_id: &TaskId) -> Vec<Artifact> {
        let list = self.artifacts.read();
        list.iter()
            .filter(|a| &a.task_id == task_id)
            .cloned()
            .collect()
    }

    pub fn all(&self) -> Vec<Artifact> {
        let list = self.artifacts.read();
        list.clone()
    }

    pub fn get(&self, artifact_id: &str) -> Option<Artifact> {
        let list = self.artifacts.read();
        list.iter().find(|a| a.id == artifact_id).cloned()
    }

    pub fn clear(&self) {
        let mut list = self.artifacts.write();
        list.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn truncation_never_exceeds_the_requested_byte_limit() {
        let value = "🌙".repeat(100);
        for limit in 0..128 {
            let truncated = truncate_text(value.clone(), limit);
            assert!(truncated.len() <= limit);
            assert!(truncated.is_char_boundary(truncated.len()));
        }
    }

    #[test]
    fn sanitize_dependency_output_strips_ansi_escapes_and_verification() {
        let raw_output = format!(
            "\x1b[32mPASS\x1b[0m tests passed\n\n\n\nFinished in 0.1s\n\n{}\n{{\"criteria\":[]}}\n{}",
            crate::verification::VERIFICATION_START,
            crate::verification::VERIFICATION_END,
        );
        let sanitized = sanitize_dependency_output(&raw_output);
        assert_eq!(sanitized, "PASS tests passed\n\nFinished in 0.1s");
    }

    #[test]
    fn sanitize_dependency_output_strips_terminal_control_sequences() {
        let raw_output = concat!(
            "before\x1b]8;;https://example.com\x07linked\x1b]8;;\x1b\\ after\n",
            "progress 10%\rprogress 100%\n",
            "hidden\x08 text\x1b7\x1b(Bdone\n",
            "\u{009b}31mgreen\u{009b}0m \u{009d}title\u{009c}plain",
        );

        assert_eq!(
            sanitize_dependency_output(raw_output),
            "beforelinked after\nprogress 10%\nprogress 100%\nhidden textdone\ngreen plain"
        );
    }
}
